# ==============================================================
# Configuracion de la aplicacion
# ==============================================================
# Aquí puedes dejar el nombre tal cual está, identifica tu proyecto.
spring.application.name=ExpedientesAPP
# El puerto 8080 está perfecto, es el puerto por defecto de Spring Boot.
server.port=8080

# Recargar plantillas Thymeleaf sin reiniciar (solo en dev)
spring.thymeleaf.cache=false

# ==============================================================
# Conexion a Oracle
# ==============================================================
# ¡OJO AQUÍ!: La URL debe llevar el formato jdbc de Oracle + el servicio + la ruta de la Wallet.
# Reemplaza 'proyectolenguajesbd_high' por el nombre del servicio que viste en tu tnsnames.ora
spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.mx-monterrey-1.oraclecloud.com))(connect_data=(service_name=g69ac3e48b7b19c_bd01_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=ProyectLenguaj
spring.datasource.password=PasswordSeguro123#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==============================================================
# JPA / Hibernate
# ==============================================================
# Hibernate crea o actualiza las tablas segun las @Entity
spring.jpa.hibernate.ddl-auto=update

# ¡OJO AQUÍ!: Como estás usando Oracle Cloud, cambia el Dialect al genérico moderno para evitar errores de compatibilidad
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Ver el SQL generado en la consola (util en clase, NO en produccion)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# Logs
# ==============================================================
logging.level.root=INFO
logging.level.com.ufide.tiendaapp=DEBUG